name: "github-php-build"
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: 'dro-oci-dev-local'
      IMAGE_NAME: 'php-demo:${{ github.run_number }}'
    permissions:
      id-token: write
      contents: read
      actions: read 
      attestations: write    
      packages: write
    # Here we install all the tools : docker buildx, QEMU, JFrog CLI, PHP - Composer
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install prerequisites
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup JFrog CLI
        id: setup-cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://${{ vars.JF_HOST }}/
          JF_PROJECT: ${{ vars.JF_PROJECT_KEY }}
        with:
            oidc-provider-name: davidro-github-integration
            oidc-audience: davidro-github
      - name: Composer Installation
        id: setup-composer-php
        uses: php-actions/composer@v6
        with:
            php_version: latest
            version: latest
            args: "--prefer-dist --optimize-autoloader"
        env:
          COMPOSER_AUTH: '{"http-basic": {"${{vars.JF_HOST}}": {"username": "${{steps.setup-cli.outputs.oidc-user}}","password": "${{steps.setup-cli.outputs.oidc-token}}"}}}'
      - name: Authenticate Docker
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.JF_HOST }}
          username: ${{ steps.setup-cli.outputs.oidc-user }}
          password: ${{ steps.setup-cli.outputs.oidc-token }}
        # docker image build
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        id: build
        with:
            push: true
            platforms: linux/amd64,linux/arm64/
            tags: ${{ vars.JF_HOST }}/${{ env.DOCKER_REPO }}/${{ env.IMAGE_NAME }}
